# Generated by Django 5.2.4 on 2026-05-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legacy_port", "0003_useritem_unique_pair"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="google_id",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
