services:
  - type: web
    name: signlingo-django
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile.django
    autoDeploy: true
    healthCheckPath: /health/
    envVars:
      - key: DJANGO_DEBUG
        value: "false"
      - key: DJANGO_SECRET_KEY
        generateValue: true
