from django.urls import path

from . import views


urlpatterns = [
    path("", views.home, name="home"),
    path("health/", views.health, name="health"),
    path("register", views.register, name="register"),
    path("login", views.login, name="login"),
    path("dashboard", views.dashboard, name="dashboard"),
    path("start", views.start, name="start"),
    path("roadmap", views.roadmap, name="roadmap"),
    path("premium", views.premium, name="premium"),
    path("package", views.package, name="package"),
    path("payment", views.payment, name="payment"),
    path("logout", views.logout, name="logout"),
    path("forgot-password", views.forgot_password, name="forgot_password"),
    path("reset_password/<str:token>", views.reset_password, name="reset_password"),
    path("leaderboard", views.leaderboard, name="leaderboard"),
    path("users", views.list_users, name="list_users"),
    path("add_friend/<int:friend_id>", views.add_friend, name="add_friend"),
    path("remove_friend/<int:friend_id>", views.remove_friend, name="remove_friend"),
    path("search-users", views.search_users, name="search_users"),
    path("save-session-results", views.save_session_results, name="save_session_results"),
    path("result-summary", views.result_summary, name="result_summary"),
    path("get-summary-results", views.get_summary_results, name="get_summary_results"),
    path("ml_game", views.ml_game, name="ml_game"),
    path("decrement_life", views.decrement_life, name="decrement_life"),
    path("video_learning", views.video_learning, name="video_learning"),
    path("gamepage", views.gamepage, name="gamepage"),
    path("mark-lesson-status", views.mark_lesson_status, name="mark_lesson_status"),
    path("course", views.course, name="course"),
    path("get-question", views.get_question, name="get_question"),
    path("get-question-ml", views.get_question_ml, name="get_question_ml"),
    path("check-answer", views.check_answer, name="check_answer"),
    path("edit-account", views.edit_account, name="edit_account"),
    path("shop", views.shop, name="shop"),
    path("buy-item", views.buy_item, name="buy_item"),
    path("magic_touch", views.magic_touch, name="magic_touch"),
]
